version: '3.5'

services:
  postgres:
    container_name: postgres-article
    image: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - ./data:/data/postgres
    ports:
      - "5433:5432"


  node_app:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "3001:3000"
    depends_on:
      - postgres 